-- NAPIŠITE PROCEDURU KOJA PRIMA @ID PROIZVODA I VRAĆA SAMO TAJ PROIZVOD IZ TABLICE PROIZVOD. POZOVITE PROCEDURU NA OBA NAČINA. UKLONITE PROCEDURU.

CREATE PROCEDURE DohvatiProizvodPoID
    @ID INT
AS
BEGIN
    SELECT * FROM Proizvod WHERE IDProizvod = @ID
END

EXEC DohvatiProizvodPoID @ID = 1
EXECUTE DohvatiProizvodPoID 1

DROP PROCEDURE DohvatiProizvodPoID
GO
-- NAPIŠITE PROCEDURU KOJA PRIMA DVIJE CIJENE I VRAĆA NAZIVE I CIJENE SVIH PROIZVODA ČIJA CIJENA JE U ZADANOM RASPONU. POZOVITE PROCEDURU NA OBA NAČINA. UKLONITE PROCEDURU

CREATE PROCEDURE DohvatiProizvodeURasponu
    @MinCijena DECIMAL(10,2),
    @MaxCijena DECIMAL(10,2)
AS
BEGIN
    SELECT Naziv, CijenaBezPDV
    FROM Proizvod
    WHERE CijenaBezPDV BETWEEN @MinCijena AND @MaxCijena
END

EXEC DohvatiProizvodeURasponu @MinCijena = 1.0, @MaxCijena = 100.00

DROP PROCEDURE DohvatiProizvodeURasponu
GO
-- NAPIŠITE PROCEDURU KOJA PRIMA ČETRI PARAMETRA POTREBNA ZA UNOS NOVE KREDITNE KARTICE. NEKA PROCEDURA NAPRAVI NOVI ZAPIS U KREDITNAKARTICA. NEKA PROCEDURA PRIJE I NAKON UMETANJA DOHVATI BROJ ZAPISA U TABLICI. POZOVITE PROCEDURU NA OBA NAČINA. UKLONITE PROCEDURU.

CREATE PROCEDURE UnesiKreditnuKarticu
    @Tip NVARCHAR(20),
    @Broj NVARCHAR(100),
    @IstekMjesec INT,
    @IstekGodina INT
AS
BEGIN
    SELECT COUNT(*) AS BrojZapisaPrije FROM KreditnaKartica

    INSERT INTO KreditnaKartica (Tip, Broj, IstekMjesec, IstekGodina)
    VALUES (@Tip, @Broj, @IstekMjesec, @IstekGodina)

    SELECT COUNT(*) AS BrojZapisaNakon FROM KreditnaKartica
END

EXEC UnesiKreditnuKarticu
    @Tip = 'Visa',
    @Broj = '1111111111111111',
    @IstekMjesec = 12,
    @IstekGodina = 2026

EXEC UnesiKreditnuKarticu
    'Visa', '2111111111111111', 6, 2026

DROP PROCEDURE UnesiKreditnuKarticu
GO

-- NAPIŠITE PROCEDURU KOJA PRIMA TRI BOJE I ZA SVAKU BOJU VRAĆA PROIZVODE U NJOJ. POZOVITE PROCEDURU I NAKON TOGA JE UKLONITE

CREATE PROCEDURE DohvatiProizvodePoBojama
    @Boja1 NVARCHAR(20),
    @Boja2 NVARCHAR(20),
    @Boja3 NVARCHAR(20)
AS
BEGIN
    SELECT * FROM Proizvod WHERE Boja = @Boja1

    SELECT * FROM Proizvod WHERE Boja = @Boja2

    SELECT * FROM Proizvod WHERE Boja = @Boja3
END

EXEC DohvatiProizvodePoBojama 'Crvena', 'Plava', 'Crna'

DROP PROCEDURE DohvatiProizvodePoBojama
GO